# Generated by Django 3.1.4 on 2021-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplan', '0003_auto_20201223_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='energy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
